/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.dinus.a112214433;

/**
 *
 * @author a112214433
 */
public class FrmMenu extends javax.swing.JFrame {

  /**
   * Creates new form NewJFrame
   */
  public FrmMenu() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    mmBarang = new javax.swing.JMenuItem();
    mmKonsumen = new javax.swing.JMenuItem();
    jSeparator1 = new javax.swing.JPopupMenu.Separator();
    mmKeluar = new javax.swing.JMenuItem();
    mmTransaksi = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jMenu1.setText("Data Master");

    mmBarang.setText("Data Barang");
    mmBarang.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mmBarangActionPerformed(evt);
      }
    });
    jMenu1.add(mmBarang);

    mmKonsumen.setText("Data Konsumen");
    mmKonsumen.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mmKonsumenActionPerformed(evt);
      }
    });
    jMenu1.add(mmKonsumen);
    jMenu1.add(jSeparator1);

    mmKeluar.setText("Keluar");
    mmKeluar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mmKeluarActionPerformed(evt);
      }
    });
    jMenu1.add(mmKeluar);

    jMenuBar1.add(jMenu1);

    mmTransaksi.setText("Transaksi");
    mmTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        mmTransaksiMouseClicked(evt);
      }
    });
    jMenuBar1.add(mmTransaksi);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void mmKonsumenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mmKonsumenActionPerformed
    new FrmKonsumen().setVisible(true);
  }// GEN-LAST:event_mmKonsumenActionPerformed

  private void mmBarangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mmBarangActionPerformed
    new FrmBarang().setVisible(true);
  }// GEN-LAST:event_mmBarangActionPerformed

  private void mmKeluarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mmKeluarActionPerformed
    dispose();
  }// GEN-LAST:event_mmKeluarActionPerformed

  private void mmTransaksiMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_mmTransaksiMouseClicked
    new FrmTransaksi().setVisible(true);
  }// GEN-LAST:event_mmTransaksiMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FrmMenu().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JPopupMenu.Separator jSeparator1;
  private javax.swing.JMenuItem mmBarang;
  private javax.swing.JMenuItem mmKeluar;
  private javax.swing.JMenuItem mmKonsumen;
  private javax.swing.JMenu mmTransaksi;
  // End of variables declaration//GEN-END:variables
}
